/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a user account (optionally claiming a guest session) */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email + password (enumeration-safe, lockout on abuse) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token or renew a guest access token
         * @description Refresh tokens are single-use; presenting a superseded token revokes the whole session family. Web clients may rely on the HttpOnly refresh cookie instead of the body field.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/guest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a room as a guest with a display name only (FR-AUTH-002) */
        post: operations["createGuestSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Logout — revoke the current session (or all devices) */
        delete: operations["endCurrentSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current actor profile facts */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /** Delete account — PII nulled, sessions revoked, content pseudonymized */
        delete: operations["deleteAccount"];
        options?: never;
        head?: never;
        /** Update display name / locale */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a couple/group room with constraint v1 and optional seed places */
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Room summary facts (members only; share code is host-only) */
        get: operations["getRoom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}/constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Host-only: new constraint version; marks scores/plans stale */
        patch: operations["updateRoomConstraints"];
        trace?: never;
    };
    "/rooms/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Host-only: validated room state transition (SRS §7.2) */
        patch: operations["transitionRoom"];
        trace?: never;
    };
    "/rooms/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Member progress facts (never other members' preference selections) */
        get: operations["listRoomMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Host-only: remove a member (revokes guest session if guest) */
        delete: operations["removeRoomMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Host-only: invite metadata (never codes) */
        get: operations["listRoomInvites"];
        put?: never;
        /** Host-only: create a high-entropy expiring invite (code shown once) */
        post: operations["createRoomInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}/invites/{inviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Host-only: revoke an invite */
        delete: operations["revokeRoomInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticated user joins via invite code */
        post: operations["joinRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/join/guest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Guest joins via invite code without an account (FR-AUTH-002) */
        post: operations["joinRoomAsGuest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}/seed-places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Host-only: attach verified places to the room (FR-ROOM-010) */
        post: operations["addRoomSeedPlaces"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{id}/seed-places/{placeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Host-only: remove a seed place */
        delete: operations["removeRoomSeedPlace"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/preferences/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Caller's own preference draft (private to the member) */
        get: operations["getMyPreferences"];
        /** Autosave with optimistic concurrency (expectedVersion) */
        put: operations["saveMyPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/preferences/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark own preferences complete; room auto-moves to matching when everyone is done */
        post: operations["completeMyPreferences"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taxonomies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stable taxonomy keys + i18n labels (clients never hard-code ids) */
        get: operations["listTaxonomies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Place search — Vietnamese-normalized text, filters, ranking, cursor
         * @description FR-SEARCH-001..004/009 + SE-010. Accent-insensitive FTS + trigram typo tolerance + synonym expansion; hard filters in SQL; weighted versioned ranking (meta.weightsVersion); stable keyset cursor. Lodging excluded unless requested. Zero-results emit telemetry without raw PII.
         */
        get: operations["searchPlaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Place detail with sources, freshness, hours, verified prices */
        get: operations["getPlaceDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run the deterministic suggestion pipeline (SG-002..005) */
        post: operations["generateSuggestions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/suggestions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current ranking, my votes, vote progress */
        get: operations["getCurrentSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/votes/{placeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Idempotent vote on a current candidate (FR-SUG-004)
         * @description Couple match mode auto-creates the plan when everyone matched.
         */
        put: operations["castVote"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/votes/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Host-only: finalize decision (tally star=2/yes=1; tie → candidate rank or host pick) */
        post: operations["finalizeVotes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/plans/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The room's current plan version with stops */
        get: operations["getCurrentPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan by id (members only) */
        get: operations["getPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Host-only: replace stop list; times/travel/costs recalculated server-side */
        patch: operations["editPlanStops"];
        trace?: never;
    };
    "/plans/{id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Host-only: regenerate — locked stops are invariant (SG-008) */
        post: operations["regeneratePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{id}/stops/{stopId}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Host-only: lock/unlock a stop */
        patch: operations["lockPlanStop"];
        trace?: never;
    };
    "/plans/{id}/stops/{stopId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a stop during the active date (FR-PLAN-008) */
        post: operations["completePlanStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{id}/stops/{stopId}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop check-in — rating/tags/note/photos, optional verified bill (FR-PLAN-008/009) */
        post: operations["checkinPlanStop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a Google Maps link for verification (FR-PLACE-001..005) */
        post: operations["submitPlaceImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places/imports/{importId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll an import (owner only) */
        get: operations["getPlaceImport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Area autocomplete proxy — provider key server-side, static fallback (FR-PLACE-007) */
        get: operations["suggestAreas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/saved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saved places/plans (FR-USER-001) */
        get: operations["listSaved"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/saved/{type}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save a place or plan (idempotent) */
        put: operations["saveItem"];
        post?: never;
        /** Remove a saved item */
        delete: operations["unsaveItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a review (moderation pending; owner-only edits — FR-USER-002) */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export all actor-owned data (privacy rule) */
        get: operations["exportMyData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** In-app notification inbox (cursor by createdAt) */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/device-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Register a push device token (BE-BFF-010) */
        put: operations["registerDeviceToken"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places/resolve-google-maps-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve a Google Maps link to a provider place (preview only)
         * @description PI-BE-018 / FR-INGEST-002/010. Hostname allowlist, ≤5 redirects with SSRF guard, no HTML scraping. Returns RESOLVED, ALREADY_EXISTS (opens the canonical place), CANDIDATE_SELECTION (user picks the branch) or UNRESOLVED with reason codes. Provider data carries source, fetchedAt and attributions; Google rating and derived score stay separate.
         */
        post: operations["resolveGoogleMapsLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/place-submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose a place from a resolved provider id (FR-INGEST-011/012)
         * @description Creates at most one pending proposal per provider place; repeat submissions increment submissionCount. Never publishes to the catalog. Guests must submit within their room-scoped session.
         */
        post: operations["submitPlace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/place-submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll a submission (owner only) */
        get: operations["getPlaceSubmission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cms/place-submissions/{id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Moderator/editor: approve, reject or merge a submission (PI-CMS-007) */
        post: operations["decidePlaceSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RoomConstraintInput: {
            originText?: string;
            originLat?: number;
            originLng?: number;
            areaKey?: string;
            radiusM?: number;
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            /** @enum {string} */
            budgetMode: "total" | "per_person";
            /** @description Integer minor units, interpreted per budgetMode. */
            budgetAmount: number;
            /** @default VND */
            currency: string;
            dietaryKeys?: string[];
            accessibilityKeys?: string[];
        };
        RoomMember: {
            /** Format: uuid */
            id: string;
            displayName: string;
            /** @enum {string} */
            role: "host" | "member";
            /** @enum {string} */
            selectionStatus: "pending" | "in_progress" | "completed";
            isGuest: boolean;
            /** Format: date-time */
            joinedAt?: string;
        };
        /** @description Facts only — audience copy is composed client-side from type/participantCount/budgetMode. */
        RoomSummary: {
            /** Format: uuid */
            id: string;
            /** @description Share code — present for the host only. */
            code?: string;
            /** @enum {string} */
            type: "couple" | "group";
            /** @enum {string} */
            status: "draft" | "collecting" | "matching" | "ready" | "active" | "completed" | "cancelled" | "expired";
            /** @enum {string} */
            decisionMode: "match" | "vote" | "host";
            participantCount: number;
            constraintVersion: number;
            title?: string;
            /** Format: date-time */
            scheduledDate?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: uuid */
            myMemberId?: string;
            /** @enum {string} */
            myRole?: "host" | "member";
            constraints?: components["schemas"]["RoomConstraintInput"];
            members?: components["schemas"]["RoomMember"][];
            seedPlaces?: {
                /** Format: uuid */
                placeId?: string;
                name?: string;
            }[];
        };
        PlaceSearchResult: {
            /** Format: uuid */
            id: string;
            name: string;
            addressText?: string;
            areaKey?: string;
            lat: number;
            lng: number;
            rating?: number;
            ratingCount?: number;
            avgVisitMinutes?: number;
            suitability?: {
                [key: string]: number;
            };
            isLodging: boolean;
            distanceM?: number;
            /** @description Estimated per-person range with confidence — never fake precision (FR-SEARCH-009). */
            pricePerPerson?: {
                min?: number;
                max?: number;
                currency?: string;
                confidence?: number;
            };
            /** @description Facts for "Đang mở · Đóng 23:00" composition client-side. */
            open: {
                openNow?: boolean;
                closesAtMinute?: number;
                opensAtMinute?: number;
                opensDayOffset?: number;
            };
            /** Format: date-time */
            freshnessCheckedAt?: string;
            confidence: number;
            reasonCodes: ("TEXT_MATCH" | "NEAR_YOU" | "HIGHLY_RATED" | "CURATED" | "OPEN_NOW")[];
        };
        TokenGrant: {
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            claimedRoomId?: string;
            accessToken: string;
            /** @description Absent for guest access renewal. */
            refreshToken?: string;
            /**
             * Format: uuid
             * @description Present for guest access renewal only.
             */
            roomId?: string;
            /** @description Access token TTL in seconds. */
            expiresIn: number;
        };
        ErrorEnvelope: {
            /** @description Stable machine-readable error code. */
            code: string;
            message: string;
            field_errors: {
                field: string;
                code: string;
                message: string;
            }[];
            request_id: string;
            retryable: boolean;
        };
        Money: {
            /** @description Integer minor units (e.g. VND has 0 decimals, amount = dong). */
            amount: number;
            currency: string;
        };
    };
    responses: {
        /** @description Validation or business rule failure */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Actor lacks permission on this resource */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Version/state conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description Client-generated key for retryable mutations. Repeating a request with the same key returns the original result instead of re-applying it. */
        IdempotencyKey: string;
        /** @description Opaque cursor from a previous page. */
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    displayName: string;
                    /** @description Opaque guest token to re-parent guest history (FR-AUTH-003). */
                    claimGuestToken?: string;
                };
            };
        };
        responses: {
            /** @description Registered; web clients also receive HttpOnly session cookies. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenGrant"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Registration could not be completed (never confirms account existence) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Authenticated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenGrant"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    refreshToken?: string;
                    guestToken?: string;
                };
            };
        };
        responses: {
            /** @description New token grant */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenGrant"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    createGuestSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    roomCode: string;
                    displayName: string;
                };
            };
        };
        responses: {
            /** @description Guest session created; access token is scoped to this room only. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        guestSessionId: string;
                        /** Format: uuid */
                        roomId: string;
                        accessToken: string;
                        /** @description Long-lived opaque credential for re-entry and claim. */
                        guestToken: string;
                    };
                };
            };
            404: components["responses"]["NotFound"];
            /** @description Room expired or no longer joinable */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    endCurrentSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default false */
                    allDevices?: boolean;
                };
            };
        };
        responses: {
            /** @description Session revoked; cookies cleared. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        revoked?: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Actor profile (shape depends on actorType) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        actorType: "user" | "guest";
                        /** Format: uuid */
                        id: string;
                        displayName?: string;
                        email?: string;
                        locale?: string;
                        /** Format: uuid */
                        roomId?: string;
                        /** Format: date-time */
                        expiresAt?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description { deleted: true } */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    displayName?: string;
                    /** @enum {string} */
                    locale?: "vi" | "en";
                };
            };
        };
        responses: {
            /** @description Updated profile facts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createRoom: {
        parameters: {
            query?: never;
            header?: {
                /** @description Client-generated key for retryable mutations. Repeating a request with the same key returns the original result instead of re-applying it. */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    type: "couple" | "group";
                    /**
                     * @description couple allows match|host; group allows vote|host.
                     * @enum {string}
                     */
                    decisionMode: "match" | "vote" | "host";
                    participantCount: number;
                    title?: string;
                    /** Format: date-time */
                    scheduledDate?: string;
                    constraint: components["schemas"]["RoomConstraintInput"];
                    seedPlaceIds?: string[];
                };
            };
        };
        responses: {
            /** @description Room created (creator becomes host) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    getRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Room summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSummary"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateRoomConstraints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomConstraintInput"] & {
                    expectedConstraintVersion: number;
                    participantCount?: number;
                };
            };
        };
        responses: {
            /** @description Updated summary with bumped constraintVersion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSummary"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    transitionRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "draft" | "collecting" | "matching" | "ready" | "active" | "completed" | "cancelled" | "expired";
                };
            };
        };
        responses: {
            /** @description Transitioned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomSummary"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    listRoomMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoomMember"][];
                };
            };
        };
    };
    removeRoomMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listRoomInvites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invites */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createRoomInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    maxUses?: number;
                };
            };
        };
        responses: {
            /** @description Invite created — plaintext code returned exactly once, only hash stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        inviteId: string;
                        code: string;
                        /** Format: date-time */
                        expiresAt: string;
                        maxUses?: number;
                    };
                };
            };
        };
    };
    revokeRoomInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    joinRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    inviteCode: string;
                };
            };
        };
        responses: {
            /** @description Joined (idempotent for existing members) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        roomId?: string;
                        /** Format: uuid */
                        memberId?: string;
                        /** @enum {string} */
                        role?: "host" | "member";
                    };
                };
            };
            /** @description Invite expired/revoked/spent or room not joinable */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    joinRoomAsGuest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    inviteCode: string;
                    displayName: string;
                };
            };
        };
        responses: {
            /** @description Guest session bound to the invite's room */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        guestSessionId?: string;
                        /** Format: uuid */
                        roomId?: string;
                        accessToken?: string;
                        guestToken?: string;
                    };
                };
            };
            /** @description Invite expired/revoked/spent */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    addRoomSeedPlaces: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    placeIds: string[];
                };
            };
        };
        responses: {
            /** @description Updated seed list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    removeRoomSeedPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated seed list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMyPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Own preferences with version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saveMyPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Taxonomy kind → selected stable keys. */
                    selections: {
                        [key: string]: string[];
                    };
                    weights?: {
                        [key: string]: number;
                    };
                    expectedVersion: number;
                };
            };
        };
        responses: {
            /** @description Saved: { version, isDraft } */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    completeMyPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description { completed, roomReadyForMatching } */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listTaxonomies: {
        parameters: {
            query?: {
                /** @description Comma-separated kind filter (mood,category,setting,dietary,accessibility,spending_style,suitability) */
                kinds?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description kinds → [{ key, sortOrder, labels }] */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    searchPlaces: {
        parameters: {
            query?: {
                q?: string;
                lat?: number;
                lng?: number;
                radiusM?: number;
                /** @description 'now' or ISO-8601 */
                openAt?: string;
                /** @description CSV */
                categories?: string;
                suitedFor?: "couple" | "group" | "family";
                priceMinPerPerson?: number;
                priceMaxPerPerson?: number;
                minRating?: number;
                /** @description CSV */
                dietary?: string;
                /** @description CSV */
                accessibility?: string;
                includeLodging?: boolean;
                sort?: "relevance" | "distance" | "rating" | "price" | "curated";
                /** @description Opaque cursor from a previous page. */
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked results with reason codes and open/price facts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        results: components["schemas"]["PlaceSearchResult"][];
                        nextCursor: string | null;
                        meta: {
                            weightsVersion?: string;
                            sort?: string;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    getPlaceDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Place aggregate (FR-PLAN-004) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    generateSuggestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked candidates with components + reason codes */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    getCurrentSuggestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run info + candidates (score */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    castVote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
                placeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    value: "yes" | "no" | "star";
                };
            };
        };
        responses: {
            /** @description { voted, matched, planId? } */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    finalizeVotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * Format: uuid
                     * @description Optional explicit winner (host mode / tie-break) — must be a current candidate.
                     */
                    placeId?: string;
                };
            };
        };
        responses: {
            /** @description { finalized, tie, winnerPlaceId, planId } */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getCurrentPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan with stops + totals (overBudget from upper bound) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan with stops */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    editPlanStops: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expectedVersion: number;
                    stops: {
                        /** Format: uuid */
                        placeId: string;
                        durationMinutes?: number;
                        /** @default false */
                        isLocked?: boolean;
                    }[];
                };
            };
        };
        responses: {
            /** @description New plan version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    regeneratePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    excludePlaceIds?: string[];
                };
            };
        };
        responses: {
            /** @description New plan version keeping every locked stop */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    lockPlanStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                stopId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    locked: boolean;
                };
            };
        };
        responses: {
            /** @description Updated plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    completePlanStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                stopId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description { completed: true } */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Conflict"];
        };
    };
    checkinPlanStop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                stopId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    rating?: number;
                    tags?: string[];
                    note?: string;
                    photoKeys?: string[];
                    /** @description Requires billPhotoKey as evidence. */
                    billTotal?: number;
                    billPeopleCount?: number;
                    billPhotoKey?: string;
                };
            };
        };
        responses: {
            /** @description Check-in saved (moderation pending); billPerPerson is display math */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    submitPlaceImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url: string;
                    /** Format: uuid */
                    roomId?: string;
                };
            };
        };
        responses: {
            /** @description Import result: pending → verified | rejected. Rejections carry a stable reasonCode (NOT_FOUND, INSUFFICIENT_REVIEWS, LOW_RATING, OUT_OF_AREA, CLOSED, INVALID_URL, PROVIDER_ERROR). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    getPlaceImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                importId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description { id, status, reasonCode?, placeId? } */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    suggestAreas: {
        parameters: {
            query: {
                query: string;
                /** @description Groups one typing session for provider billing. */
                sessionToken: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description { predictions[], source: provider|fallback, attribution } */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listSaved: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    saveItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: "place" | "plan";
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unsaveItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: "place" | "plan";
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    placeId?: string;
                    /** Format: uuid */
                    planId?: string;
                    rating: number;
                    text?: string;
                };
            };
        };
        responses: {
            /** @description { id, status: pending } */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exportMyData: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON export; audit-logged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                /** @description Opaque cursor from a previous page. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description { notifications[], nextCursor } */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registerDeviceToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    platform: "ios" | "android" | "web";
                    token: string;
                };
            };
        };
        responses: {
            /** @description Registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resolveGoogleMapsLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uri */
                    url: string;
                    cityHint?: string;
                    /** Format: uuid */
                    roomId?: string;
                };
            };
        };
        responses: {
            /** @description Resolution outcome with candidate/attribution facts */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    submitPlace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    googlePlaceId: string;
                    /** Format: uuid */
                    roomId?: string;
                    category?: string;
                    estimatedPrice?: {
                        min?: number;
                        max?: number;
                        /** @enum {string} */
                        unit?: "per_person" | "per_group" | "per_item" | "free" | "unknown";
                    };
                    vibes?: string[];
                    note?: string;
                };
            };
        };
        responses: {
            /** @description PENDING (with submissionId/deduped) or ALREADY_EXISTS (with placeId) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            /** @description Place is closed/suspended and cannot be added */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getPlaceSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description { id, status, placeId?, submissionCount } */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    decidePlaceSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    decision: "approved" | "rejected" | "merged";
                    reason: string;
                    /** Format: uuid */
                    mergeIntoPlaceId?: string;
                };
            };
        };
        responses: {
            /** @description Decision applied; audited + reindex event emitted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
}
